# Generated by Django 3.0.5 on 2020-05-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bcontent',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bintro',
            field=models.TextField(default='此书暂无简介', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bpic',
            field=models.CharField(default='暂无图片', max_length=100),
        ),
    ]
