# Generated by Django 3.0.5 on 2020-05-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200513_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='btype',
            field=models.CharField(default='小说', max_length=20),
        ),
    ]
