# Generated by Django 3.0.5 on 2020-05-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bookinfo_btype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bname',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
