# Generated by Django 3.0.5 on 2020-05-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200514_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
