# Generated by Django 3.0.5 on 2020-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200514_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bname',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
