# Generated by Django 3.0.5 on 2020-05-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200514_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bauthor',
            field=models.CharField(blank=True, default='不详', max_length=40),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bout',
            field=models.CharField(blank=True, default='未知', max_length=40),
        ),
    ]
