# Generated by Django 3.0.5 on 2020-05-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200514_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PicTest',
        ),
    ]
