# Generated by Django 3.0.5 on 2020-05-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_pictest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='users', verbose_name='pic')),
            ],
            options={
                'db_table': 'PicTest',
            },
        ),
    ]
