# Generated by Django 3.0.5 on 2020-05-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_pictest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PicTest',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uimage',
            field=models.ImageField(default=1, upload_to='users'),
            preserve_default=False,
        ),
    ]
