# Generated by Django 3.0.5 on 2020-05-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200517_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='uimage',
        ),
    ]
